#!/bin/bash
sudo apt install -y wget vim openjdk-8-jdk openjdk-8-jre
echo "installed wget, vim, jdk and jre"
sudo useradd --create-home jenkins
sudo usermod --shell /bin/bash jenkins
echo "user created: jenkins, permission granted to only run Jenkins"
sudo su - jenkins -c wget http://updates.jenkins-ci.org/latest/jenkins.war
echo "downloaded latest jenkins version"
sudo cat > /etc/systemd/system/jenkins.service << END
[UNIT]
Description=Jenkins

[Service]
User=jenkins
WorkingDirectory=/home/jenkins
ExecStart=/usr/bin.java -jar /home/jenkins/jenkins.war

[Install]
WantedBy=multi-user.target
END
sudo systemctl daemon-reload
sudo systemctl start jenkins
echo "jenkins started"
